### PR TITLE
Base1.1

### PR DESCRIPTION
**Pull request by redheadedrod**
First attempt... For some reason seems to be showing way more changes than supposed to be.

### CODE REVIEW

**Comment by atlas0fd00m** [comment]
i'm guessing you had some improvements to master merged in.  i've just pulled and merged the lastest master into atlas_arm_fixes.  please do the same, and then merge that into your PR branch.

**Comment by redheadedrod** [comment]
Looks way better. Will try to get the others posted... And update the first one.

**Comment by atlas0fd00m** [comment]
still need to clear the conflicts, sorry.  i can't even try to merge it until they're cleaned up.

**Comment by atlas0fd00m** [comment]
this still has conflict as well.

**Pull request merged**
